# Generated by Django 4.1.3 on 2022-11-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название курса')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('level_training', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='EASY', max_length=6, verbose_name='Уровень тяжести')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Курс тренировок',
                'verbose_name_plural': 'Курсы тренировок',
            },
        ),
    ]
